/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Office(props) {
  const { nodes, materials } = useGLTF("models/scene.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tempat_minum.geometry}
        material={materials.PaletteMaterial001}
        position={[-3.12, 3.126, -2.152]}
        scale={[0.98, 0.144, 0.329]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tatakan_laptop.geometry}
        material={materials.PaletteMaterial002}
        position={[-3.61, 3.375, 1.255]}
        scale={[1.003, 11.242, 1.003]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.saklar.geometry}
        material={materials["Wood.119"]}
        position={[1.943, 4.753, 4.108]}
        scale={[0.326, 0.198, 0.049]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.poster.geometry}
        material={materials.poster}
        position={[3.053, 6.645, 4.106]}
        scale={[1, 1.49, 0.055]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.blanket.geometry}
        material={materials["Colorful Flower Fabric"]}
        position={[2.971, 1.142, -0.511]}
        scale={[1.691, 1.092, 3.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.layar_monitor_2.geometry}
        material={materials["layar monitor 2"]}
        position={[-3.347, 4.326, -0.771]}
        rotation={[0, -0.502, 0]}
        scale={[0.024, 0.63, 1.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.layar_monitor_1.geometry}
        material={materials["layar monitor 1"]}
        position={[-3.151, 4.326, 3.149]}
        rotation={[0, 0.698, 0]}
        scale={[0.024, 0.63, 1.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.poto_21.geometry}
        material={materials["poto 2.1"]}
        position={[-2.468, 6.62, 4.068]}
        scale={[0.708, 1.423, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.poto_11.geometry}
        material={materials["poto 1.1"]}
        position={[-0.416, 7.324, 3.969]}
        scale={[1.135, 0.711, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.poto_31.geometry}
        material={materials["poto 3.1"]}
        position={[-1.02, 5.828, 3.98]}
        scale={[0.549, 0.636, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.poto_41.geometry}
        material={materials["poto 4.1"]}
        position={[0.212, 5.828, 3.948]}
        scale={[0.536, 0.628, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Wood.121"]}
        position={[-0.889, 3.771, -0.057]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[16.949, 5.321, 4.122]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lantai.geometry}
        material={materials["Wooden floor.001"]}
        scale={[4.364, 0.114, 4.364]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tembok_kanan.geometry}
        material={materials["Decorated Wall 01"]}
        position={[0, 4.249, -0.005]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[167.601, 4.364, 167.601]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["1"].geometry}
        material={materials["Wood.120"]}
        position={[0.093, 4.115, -0.039]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[48.938, 4.257, 32.008]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stop_kontak.geometry}
        material={materials["Perforated rubber"]}
        position={[-3.968, 2.612, -0.516]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.174, 0.184, 0.803]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.layar_laptop.geometry}
        material={materials.PaletteMaterial004}
        position={[-4.06, 4.336, 1.256]}
        scale={[0.022, 0.568, 0.995]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.badan_laptop.geometry}
        material={materials.PaletteMaterial005}
        position={[-3.59, 3.428, 1.254]}
        rotation={[0, 0, 0.935]}
        scale={[0.028, 0.612, 0.994]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.layar_monitor_laptop.geometry}
        material={materials["layar monitor laptop"]}
        position={[-4.048, 4.369, 1.252]}
        scale={[0.022, 0.486, 0.963]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.luaran_key_Laptop.geometry}
        material={materials.PaletteMaterial006}
        position={[-3.719, 3.552, 1.263]}
        rotation={[0, 0, 0.935]}
        scale={[0.013, 0.354, 0.89]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trackpad_laptop.geometry}
        material={materials.PaletteMaterial007}
        position={[-3.265, 3.222, 1.255]}
        rotation={[0, 0, 0.935]}
        scale={[0.01, 0.199, 0.397]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Badan_Keyboard.geometry}
        material={materials.PaletteMaterial008}
        position={[-2.663, 3.062, 1.246]}
        rotation={[-1.571, -0.004, 1.571]}
        scale={[-2.349, 0.721, 0.114]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mousepad.geometry}
        material={materials.PaletteMaterial009}
        position={[-2.997, 3.958, 0.781]}
        scale={[32.508, 1.031, 85.543]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.button_trackpad_2.geometry}
        material={materials.PaletteMaterial010}
        position={[-3.136, 3.131, 1.058]}
        rotation={[0, 0, -2.206]}
        scale={[-0.019, 0.203, 0.806]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kasur.geometry}
        material={materials["Colorful flower fabric"]}
        position={[2.942, 0.86, 0.329]}
        scale={[1.313, 0.222, 3.524]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lampu_terang001.geometry}
        material={materials["Rough Iron Steel"]}
        position={[-4.007, 2.618, 2.103]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.054, 1.976, 0.054]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Office_chair.geometry}
        material={materials.fabric}
        position={[-0.576, 3.134, 1.229]}
        rotation={[0, 1.563, 0]}
        scale={[1.515, 1.443, 1.256]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plate4.geometry}
        material={materials["Wood Variant 4"]}
        position={[-0.018, 0.063, 0.03]}
        scale={[0.102, 1.015, 1.015]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.PaletteMaterial011}
        position={[2.962, 1.481, 2.952]}
        rotation={[-0.431, 0, 0]}
        scale={[7.154, 0.411, 5.745]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MouseThermaltakeBlack.geometry}
        material={materials.PaletteMaterial012}
        position={[-2.773, 3.138, -0.381]}
        rotation={[Math.PI / 2, 0, -1.99]}
        scale={[0.127, 0.09, 0.111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MouseThermaltakeBlack002.geometry}
        material={materials.PaletteMaterial013}
        position={[-2.729, 3.133, -0.326]}
        rotation={[Math.PI / 2, 0, -1.99]}
        scale={[0.121, 0.112, 0.138]}
      />
      <group
        position={[-2.659, 3.097, -0.425]}
        rotation={[Math.PI / 2, 0, -1.99]}
        scale={[0.281, 0.261, 0.323]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MouseThermaltakeBlack003_1.geometry}
          material={materials.PaletteMaterial014}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MouseThermaltakeBlack003_2.geometry}
          material={materials.PaletteMaterial015}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MouseThermaltakeBlack005.geometry}
        material={materials.PaletteMaterial016}
        position={[-2.65, 3.082, -0.431]}
        rotation={[Math.PI / 2, 0, -1.99]}
        scale={[0.245, 0.228, 0.281]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MouseThermaltakeBlack008.geometry}
        material={materials.PaletteMaterial017}
        position={[-2.819, 3.127, -0.362]}
        rotation={[Math.PI / 2, 0, -1.99]}
        scale={[0.039, 0.036, 0.045]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MouseThermaltakeBlack012.geometry}
        material={materials.PaletteMaterial018}
        position={[-2.654, 3.097, -0.434]}
        rotation={[Math.PI / 2, 0, -1.99]}
        scale={[0.288, 0.268, 0.33]}
      />
    </group>
  );
}

useGLTF.preload("models/scene.glb");
